name: Deploy Docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: docs
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Merge in master
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin master --no-edit --allow-unrelated-histories --no-rebase
      - name: Build docs
        run: yarn install && yarn build:storybook
      - name: Push to docs branch
        run: |
          git add .
          git commit -m "generated latest docs build from master"
          git push origin docs -f
