name: NPM Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          file-url: https://unpkg.com/@lambdacurry/component-library/package.json
          static-checking: localIsNew
      - uses: actions/setup-node@v1
        if: steps.check.outputs.changed == 'true'
        with:
          node-version: 14
      - name: Install Dependencies
        if: steps.check.outputs.changed == 'true'
        run: yarn && yarn build
      - name: Prepare & Publish
        if: steps.check.outputs.changed == 'true'
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_SECRET }}
      - if: steps.publish.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
